### ISSUE TITLE
JOI dataset

### ISSUE THREAD

**Issue by ZnPdCo** [conlacda/atcoder-companion#9]
Dataset can be found at https://www2.ioi-jp.org/camp/

example problem: https://atcoder.jp/contests/joisc2022/tasks/joisc2022_k

**Comment by conlacda** [comment]
@ZnPdCo 
I created branch **[joisc2022](https://github.com/conlacda/atcoder-testcases/tree/joisc2022)**. Can you help me to make a pull request?

**Comment by ZnPdCo** [comment]
I think this should be automatically crawled instead of manually updated.

**Comment by ZnPdCo** [comment]
Why is there a downloader.py file in every branch

**Comment by conlacda** [comment]
@ZnPdCo 

> I think this should be automatically crawled instead of manually updated.

Basically, the test cases that are published on Dropbox will be downloaded. The above contest is an external contest, so I do not have enough time to check every contest. I think for this type of contest, downloading manually and then committing is faster than writing a script for them.

> Why is there a downloader.py file in every branch

Because I run git checkout branch for every new branch. (Note that it is impossible to put them into a single branch.).

**Comment by conlacda** [comment]
https://github.com/conlacda/atcoder-testcases/pull/1
